### ISSUE TITLE
/upload page spec visual modif

### ISSUE THREAD

**Issue by lucasverra** [lucasverra/b-b#14]
Please check spec file for ressources and comment here on our improvement for upload page. 

Since you didn't start on layouting, we thought of this mod. Is this ~ same level of complexity? @gsanikidze 

<img width="768" alt="image" src="https://user-images.githubusercontent.com/11323803/57153396-7e3f0900-6dd6-11e9-8f71-b467d31534c5.png">

--- 

![](https://trello-attachments.s3.amazonaws.com/5b69555b6a186923bdd929e0/5ccb0fcb09c13d062d8688e3/8c16a36427cf2a96075ed69e561fae3f/image.png)

**Comment by tmsmldr** [comment]
Ressources

https://trello-attachments.s3.amazonaws.com/5b69555b6a186923bdd929e0/5ccb0fcb09c13d062d8688e3/7f0b95961b8cf9bfb3fff70558a1b3bf/plus-button.png

https://trello-attachments.s3.amazonaws.com/5b69555b6a186923bdd929e0/5ccb0fcb09c13d062d8688e3/d07bb6010ef4681e988ee277503a41ad/jajka.png

https://trello-attachments.s3.amazonaws.com/5b69555b6a186923bdd929e0/5ccb0fcb09c13d062d8688e3/ae8474cf88780080b05fc2f8d99f3474/sillon.png
