### ISSUE TITLE
different filter boxes are related by attributes, that should not be the case

### ISSUE THREAD

**Issue by lucasverra** [lucasverra/b-b#16]
video here => https://www.useloom.com/share/527225611f1445c9b227bb1c638bbdc7

in plain words : 

there is some form of complementarity between attributes from one box to another box (of the same model). That is not good 🆘

in the video it's clear that attributes selected in 2nd box have an impact on counting in the first box. 
I think you'r implementation is treating the `model` as the `lowest level`, when you should use the `individual box` as the lowest level of [counting+selection model item from buttons activity]

>Specification
>There are 2 differents types of record-counting actions that the app have to perform

>Record counting of the selection of an individual box
Record counting of the total records that will be exported. 

>These actions has to be performed automatically and triggered by any change on the state of the buttons selection.

>Each box should have its own count and the total count will be presented at the bottom of the page

>Criteria selection and counting logic.

>On Individual Boxes

>Each box use the same logic to count the number of records that meet the criteria defined by the button selection. The only thing that could change from one box to another is eventually the model that is defined in the section.

>The state of the selection buttons will be used to populate a query asking the database for the count of the records that meet the criteria. The conditional criteria used is a simple “OR” and “AND” logic. 

>Between values of the same attribute there will be an “OR” type of condition
Between Attributes of the individual bor there will an “AND” type of condition 

>In other words. For each box, the app should ask the data base to count only for the records that correspond to a particular model  but only if they have, ANY of the colours selected but only if they have, ANY of the type of furniture selected but only if they have, ANY of the tissues selected, but only if they have, ANY of the pieds selected.

>If no value is selected for an attribute then the system should ask for an empty or null value in that attribut.

>Ex GET Records or COUNT Records 
Box 1 > Model [M1] AND Color [ c1 OR c2 OR, ... ] AND Category  [ cat1 OR cat2 OR, ... ] AND Toucher [ t1 OR t2 OR, ... ] AND Pieds [ p1 OR p2 OR, ... ]

**Comment by lucasverra** [comment]
https://www.loom.com/share/96a741139b4a43d3a73fff651d5cf778 

bug on a 3rd level box filter

**Comment by lucasverra** [comment]
check this edge case on tomas file

**Comment by tmsmldr** [comment]
Hello Guram I realise 2 little things that can maybe help you finding the 2 problems encounter here (the 2 videos in previous comments)

For the first problem (the 3rd box problem) > When a 3rd box is open even if nothing is selected automatically the total count stop taking in cosideration the selection in the second box and it only reads the 1st box.

For the 2 problem (the bug on total counter) > It seems to me that  the little bug is only a matter of where you click . if i click on the 2d box the total count take in consideration the first box & the 2d box and the total counting is good, working as specified.  In the other hand if i had open a 2do box and I come back to the first box and make change then the total count forgets the 2ndo box only take in consideration the first box. 

It seems to me that the code is "telling" the total counter which precise boxes to take into consideration depending on where you click. It might be a bad idea depending on how you code it bout If it can help to get trough the problem, we can set a limited number of boxes to the models block. For example only 10 boxes max per model.
