### ISSUE TITLE
heigh of cell seem not confortable

### ISSUE THREAD

**Issue by lucasverra** [lucasverra/b-b#19]
![image](https://user-images.githubusercontent.com/11323803/57571870-8cfb7080-7413-11e9-9034-1ba1ec2a228c.png)

to mee its to big, @tmsmldr what do you say ?

**Comment by gsanikidze** [comment]
@lucasverra there is lots of text. Heigh is more in original file.
One way to minimize height is to make width more.

**Comment by lucasverra** [comment]
but in original file, the heigh of lines is smaller right ? what is the difference ?

**Comment by tmsmldr** [comment]
Hello @gsanikidze , do not worry if the entire text does not show on the cell. Just force the height to 40 in excel height unites. As it is in the Output File template

![image](https://user-images.githubusercontent.com/22592862/57582119-22087300-74c1-11e9-9987-618a8fc3ec71.png)

![image](https://user-images.githubusercontent.com/22592862/57582129-38163380-74c1-11e9-9cbd-b03318668084.png)
