### ISSUE TITLE
error handling when getting images

### ISSUE THREAD

**Issue by lucasverra** [lucasverra/b-b#28]
we do not provide basic error image workflow. 
if assets is not found (bad url), excel files is not created. 

we should return in the cell : 

- error , 404 

or

- error, not an image 

or 

- error timeout (after 90s)

**Comment by lucasverra** [comment]
error message should go in cell (excel) not in browser. 
In actual situation, any error cancels export file generation. that is not the desired situation

**Comment by gsanikidze** [comment]
if there is any error it will write inside browser, in other way why you need file with error?

**Comment by lucasverra** [comment]
its not that i need file with error, but the way we are handling now (canceling file generation if  at least 1 error) there is small chances to get an actual excel export.
