### ISSUE TITLE
model to the bottom when click on Model 

### ISSUE THREAD

**Issue by lucasverra** [lucasverra/b-b#5]
As seen in video https://www.loom.com/share/28e9117035994cf1954e4275c4ecb852, 

when i click on a button, that specific model box moves automatically to the bottom of the layout . That is not OK

**Comment by gsanikidze** [comment]
@lucasverra I think i already fixed this issue or i can't find it, hire is video - https://www.loom.com/share/1d26db90c88749e3864f9bad0c10502e

**Comment by lucasverra** [comment]
Indeed it, that is the expected functionality, meaning having to click and not having model boxes changing positions

**Comment by lucasverra** [comment]
i still have it online 

https://www.loom.com/share/04746385cb664f5c960aab5a6704b514

**Comment by lucasverra** [comment]
i just realize its on safari, not chrome
